name: Windows Executables
on:
  push:
    # branches:
    #   - main
    paths-ignore:
      - 'docs/**'
jobs:
  build:
    strategy:
      matrix:
        project: [qeels, nanomi-optics, alignment-software]
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./${{ matrix.project }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Build Execeutable
        run: poetry run pyinstaller -F main.py --name ${{ matrix.project }}
      - name: Build Execeutable
        run: poetry run pyinstaller -F main.py --name ${{ matrix.project }}
      - name: Upload Execeutable
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.project }}
          path: ${{ matrix.project }}/dist/${{ matrix.project }}.exe
