name: Linting
on: [push]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.X'
          cache: 'pip'
      - name: Install Flake8
        run: pip install flake8
      - name: Lint nrcemt package
        run: flake8 nrcemt
